name: Testing all components

on:
  pull_request:
    branches: [main]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install all dependencies
        run: npm ci

      - name: Testing
        run: npm run test
